pipeline {
    agent any
    tools {
        gradle 'gradle'
    }
    stages {
        stage('Git Clone') {
            steps {
                git branch: 'feature-cicdtest-be', url: 'https://lab.ssafy.com/s09-fintech-finance-sub2/S09P22D106.git', credentialsId: 'gitlab-noah-credentials'
            }
        }
        stage('BE-Build') {
            steps {
                dir("./BE/Gudgenet") {
                    sh "chmod +x ./gradlew"
                    sh "./gradlew clean build"
                }
            }
        }
        stage('deploy'){
                steps{
                    sh 'docker-compose up -d --build'
            }
        }
    }
}