pipeline {
    agent any
    
    stages {
        stage('Git Clone') {
            steps {
                git branch: 'master', url: 'https://lab.ssafy.com/s09-fintech-finance-sub2/S09P22D106.git', credentialsId: 'kmsToken'
            }
        }
        stage('Build and Deploy'){
            steps{
                dir("./Flask") { // Flask 앱 디렉터리로 변경
                    sh 'docker-compose up -d --build'
                }
            }
        }
        stage('Clean Up'){
            steps{
                sh "docker image prune -f"
            }
        }
    }
}
